-- Aeroheights Travels & Tours CRM - full database schema (structure only).
-- Import into an EMPTY database (phpMyAdmin > Import, or the setup script). Contains no USE statement on purpose.
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `agent_adjustments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `agent_id` int(10) unsigned NOT NULL,
  `adjustment_date` date NOT NULL,
  `amount_sar` decimal(12,2) NOT NULL,
  `reason` varchar(255) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_aa_agent` (`agent_id`),
  KEY `idx_aa_date` (`adjustment_date`),
  CONSTRAINT `fk_aa_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `agent_payments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `agent_id` int(10) unsigned NOT NULL,
  `payment_date` date NOT NULL,
  `bank_account_id` int(10) unsigned DEFAULT NULL,
  `bank_name` varchar(150) NOT NULL,
  `amount_pkr` decimal(15,2) NOT NULL,
  `exchange_rate` decimal(8,2) NOT NULL DEFAULT 76.00,
  `amount_sar` decimal(12,2) NOT NULL,
  `receipt_number` varchar(100) DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_ap_agent` (`agent_id`),
  KEY `idx_ap_date` (`payment_date`),
  KEY `fk_ap_bank` (`bank_account_id`),
  CONSTRAINT `fk_ap_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ap_bank` FOREIGN KEY (`bank_account_id`) REFERENCES `bank_accounts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `agents` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `company_name` varchar(150) DEFAULT NULL,
  `phone` varchar(50) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `city` varchar(100) DEFAULT 'Lahore',
  `address` text DEFAULT NULL,
  `opening_balance_sar` decimal(12,2) DEFAULT 0.00,
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `air_tickets` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `ticket_no` varchar(20) NOT NULL DEFAULT '',
  `pnr` varchar(20) DEFAULT NULL,
  `airline_code` varchar(3) DEFAULT NULL,
  `airline_name` varchar(80) DEFAULT NULL,
  `family_head` varchar(120) DEFAULT NULL,
  `pax_count` int(10) unsigned NOT NULL DEFAULT 0,
  `route` varchar(120) DEFAULT NULL,
  `dep_date` date DEFAULT NULL,
  `ret_date` date DEFAULT NULL,
  `status` varchar(30) DEFAULT NULL,
  `is_booking` tinyint(1) NOT NULL DEFAULT 0,
  `booking_date` date DEFAULT NULL,
  `agent_id` int(10) unsigned DEFAULT NULL,
  `vendor_id` int(10) unsigned DEFAULT NULL,
  `buy_pkr` decimal(12,2) NOT NULL DEFAULT 0.00,
  `sell_pkr` decimal(12,2) NOT NULL DEFAULT 0.00,
  `booking_remarks` varchar(500) DEFAULT NULL,
  `original_filename` varchar(200) DEFAULT NULL,
  `original_path` varchar(255) DEFAULT NULL,
  `original_mime` varchar(60) DEFAULT NULL,
  `passport_files` longtext DEFAULT NULL,
  `ai_notes` varchar(1000) DEFAULT NULL,
  `payload` longtext NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_at_pnr` (`pnr`),
  KEY `idx_at_dep_date` (`dep_date`),
  KEY `idx_at_is_booking` (`is_booking`),
  KEY `idx_at_booking_date` (`booking_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `audit_logs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `entity_type` varchar(100) NOT NULL,
  `entity_id` bigint(20) unsigned NOT NULL,
  `action` varchar(100) NOT NULL,
  `old_values` longtext DEFAULT NULL,
  `new_values` longtext DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_audit_entity` (`entity_type`,`entity_id`),
  KEY `idx_audit_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `bank_accounts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `bank_name` varchar(150) NOT NULL,
  `account_title` varchar(150) NOT NULL,
  `account_number` varchar(100) NOT NULL,
  `branch_code` varchar(50) DEFAULT NULL,
  `opening_balance_pkr` decimal(15,2) DEFAULT 0.00,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `booking_files` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `attachment_type` enum('visa','ticket','passport') NOT NULL,
  `original_filename` varchar(255) NOT NULL,
  `stored_filename` varchar(255) NOT NULL,
  `storage_path` varchar(500) NOT NULL,
  `mime_type` varchar(100) NOT NULL DEFAULT 'application/pdf',
  `file_size` bigint(20) unsigned NOT NULL DEFAULT 0,
  `download_token_hash` char(64) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_booking_file_token` (`download_token_hash`),
  KEY `idx_booking_files_booking_type` (`booking_id`,`attachment_type`,`deleted_at`),
  CONSTRAINT `fk_booking_files_booking` FOREIGN KEY (`booking_id`) REFERENCES `master_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `hotel_booking_master_links` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `hotel_booking_id` int(10) unsigned NOT NULL,
  `master_booking_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_hbml_link` (`hotel_booking_id`,`master_booking_id`),
  KEY `idx_hbml_hotel_booking` (`hotel_booking_id`),
  KEY `idx_hbml_master_booking` (`master_booking_id`),
  CONSTRAINT `fk_hbml_hotel_booking` FOREIGN KEY (`hotel_booking_id`) REFERENCES `hotel_bookings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hbml_master_booking` FOREIGN KEY (`master_booking_id`) REFERENCES `master_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `hotel_booking_stays` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `city` varchar(100) NOT NULL DEFAULT 'Makkah',
  `hotel_name` varchar(150) NOT NULL,
  `room_type` varchar(100) NOT NULL DEFAULT 'Double Bed',
  `meal_plan` varchar(50) NOT NULL DEFAULT 'RO',
  `confirmation_number` varchar(100) DEFAULT NULL,
  `checkin_date` date NOT NULL,
  `checkout_date` date NOT NULL,
  `nights` int(10) unsigned NOT NULL DEFAULT 1,
  `rooms` int(10) unsigned NOT NULL DEFAULT 1,
  `buy_rate_per_night` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sell_rate_per_night` decimal(10,2) NOT NULL DEFAULT 0.00,
  `buy_total` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sell_total` decimal(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `idx_hbs_booking` (`booking_id`),
  KEY `idx_hbs_checkin` (`checkin_date`),
  CONSTRAINT `fk_hbs_booking` FOREIGN KEY (`booking_id`) REFERENCES `hotel_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `hotel_bookings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_ref` varchar(50) NOT NULL,
  `booking_date` date NOT NULL,
  `agent_id` int(10) unsigned NOT NULL,
  `total_nights` int(10) unsigned NOT NULL DEFAULT 0,
  `lead_guest_name` varchar(150) NOT NULL,
  `company_name` varchar(150) NOT NULL DEFAULT 'Ajmal S Travel & Tours',
  `pax_adults` int(10) unsigned NOT NULL DEFAULT 1,
  `pax_children` int(10) unsigned NOT NULL DEFAULT 0,
  `pax_infants` int(10) unsigned NOT NULL DEFAULT 0,
  `remarks` text DEFAULT NULL,
  `transport_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `transport_type` varchar(100) DEFAULT NULL,
  `transport_buy_rate` decimal(10,2) NOT NULL DEFAULT 0.00,
  `transport_sell_rate` decimal(10,2) NOT NULL DEFAULT 0.00,
  `buy_total_sar` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sell_total_sar` decimal(10,2) NOT NULL DEFAULT 0.00,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `booking_ref` (`booking_ref`),
  KEY `idx_hb_ref` (`booking_ref`),
  KEY `idx_hb_agent` (`agent_id`),
  CONSTRAINT `fk_hb_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `hotel_stays` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `line_item_id` varchar(64) NOT NULL,
  `sequence` int(10) unsigned NOT NULL DEFAULT 1,
  `city` varchar(100) DEFAULT 'Makkah',
  `hotel_name` varchar(150) NOT NULL,
  `room_type` varchar(100) DEFAULT 'Double Bed',
  `checkin_date` date NOT NULL,
  `checkout_date` date NOT NULL,
  `nights` int(10) unsigned NOT NULL DEFAULT 1,
  `per_night_buy` decimal(12,2) NOT NULL DEFAULT 0.00,
  `per_night_sell` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'SAR',
  `meal_plan` varchar(50) DEFAULT 'RO',
  `view` varchar(100) DEFAULT NULL,
  `pax` int(10) unsigned NOT NULL DEFAULT 1,
  `net_accommodation_charge` decimal(12,2) NOT NULL DEFAULT 0.00,
  `vat` decimal(12,2) NOT NULL DEFAULT 0.00,
  `notes` varchar(255) DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hs_line_item` (`line_item_id`),
  KEY `idx_hs_booking` (`booking_id`),
  KEY `idx_hs_dates` (`checkin_date`,`checkout_date`),
  CONSTRAINT `fk_hs_booking` FOREIGN KEY (`booking_id`) REFERENCES `master_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `hotel_voucher_master_links` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `voucher_id` int(10) unsigned NOT NULL,
  `master_booking_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_hvml_link` (`voucher_id`,`master_booking_id`),
  KEY `idx_hvml_voucher` (`voucher_id`),
  KEY `idx_hvml_master_booking` (`master_booking_id`),
  CONSTRAINT `fk_hvml_master_booking` FOREIGN KEY (`master_booking_id`) REFERENCES `master_bookings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hvml_voucher` FOREIGN KEY (`voucher_id`) REFERENCES `hotel_vouchers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `hotel_vouchers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `voucher_no` varchar(50) NOT NULL,
  `voucher_date` date NOT NULL,
  `master_booking_id` int(10) unsigned DEFAULT NULL,
  `agent_id` int(10) unsigned NOT NULL,
  `vendor_id` int(10) unsigned DEFAULT NULL,
  `family_head` varchar(150) NOT NULL,
  `company_name` varchar(150) NOT NULL DEFAULT 'Ajmal S Travel & Tours',
  `package_name` varchar(150) DEFAULT NULL,
  `total_pax` int(10) unsigned DEFAULT 1,
  `total_beds` int(10) unsigned DEFAULT 1,
  `total_nights` int(10) unsigned DEFAULT 0,
  `transporter_info` varchar(255) DEFAULT 'Company Transport',
  `transport_type` varchar(100) DEFAULT NULL,
  `flight_out_no` varchar(50) DEFAULT NULL,
  `flight_out_from` varchar(100) DEFAULT NULL,
  `flight_out_to` varchar(100) DEFAULT NULL,
  `flight_out_dep_date` date DEFAULT NULL,
  `flight_out_dep_time` time DEFAULT NULL,
  `flight_out_arr_date` date DEFAULT NULL,
  `flight_out_arr_time` time DEFAULT NULL,
  `flight_ret_no` varchar(50) DEFAULT NULL,
  `flight_ret_from` varchar(100) DEFAULT NULL,
  `flight_ret_to` varchar(100) DEFAULT NULL,
  `flight_ret_dep_date` date DEFAULT NULL,
  `flight_ret_dep_time` time DEFAULT NULL,
  `flight_ret_arr_date` date DEFAULT NULL,
  `flight_ret_arr_time` time DEFAULT NULL,
  `buy_rate_sar` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sell_rate_sar` decimal(10,2) NOT NULL DEFAULT 0.00,
  `special_instructions` text DEFAULT NULL,
  `transport_auto_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `transport_auto_type` varchar(100) DEFAULT NULL,
  `transport_auto_buy_rate` decimal(10,2) NOT NULL DEFAULT 0.00,
  `transport_auto_sell_rate` decimal(10,2) NOT NULL DEFAULT 0.00,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `voucher_no` (`voucher_no`),
  KEY `idx_hv_voucher_no` (`voucher_no`),
  KEY `idx_hv_agent` (`agent_id`),
  KEY `idx_hv_mb` (`master_booking_id`),
  KEY `fk_hv_vendor` (`vendor_id`),
  CONSTRAINT `fk_hv_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hv_mb` FOREIGN KEY (`master_booking_id`) REFERENCES `master_bookings` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hv_vendor` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `master_bookings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_code` varchar(50) NOT NULL,
  `booking_date` date DEFAULT NULL,
  `agent_id` int(10) unsigned DEFAULT NULL,
  `vendor_id` int(10) unsigned DEFAULT NULL,
  `passenger_name` varchar(150) DEFAULT NULL,
  `passport_number` varchar(50) DEFAULT NULL,
  `flight_number` varchar(50) DEFAULT NULL,
  `arrival_date` date DEFAULT NULL,
  `departure_date` date DEFAULT NULL,
  `stay_days` varchar(50) DEFAULT NULL,
  `buy_rate_sar` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sell_rate_sar` decimal(10,2) NOT NULL DEFAULT 0.00,
  `ticket_buy_rate_sar` decimal(10,2) NOT NULL DEFAULT 0.00,
  `ticket_sell_rate_sar` decimal(10,2) NOT NULL DEFAULT 0.00,
  `attach_hotel` tinyint(1) NOT NULL DEFAULT 0,
  `attach_transport` tinyint(1) NOT NULL DEFAULT 0,
  `remarks` varchar(255) DEFAULT NULL,
  `status` enum('draft','confirmed','issued','completed','cancelled') NOT NULL DEFAULT 'draft',
  `custom_field1` text DEFAULT NULL,
  `custom_field2` text DEFAULT NULL,
  `custom_fields_json` longtext DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `booking_code` (`booking_code`),
  UNIQUE KEY `uq_master_booking_code` (`booking_code`),
  KEY `idx_mb_booking_code` (`booking_code`),
  KEY `idx_mb_agent` (`agent_id`),
  KEY `idx_mb_vendor` (`vendor_id`),
  KEY `idx_mb_arrival` (`arrival_date`),
  KEY `idx_mb_departure` (`departure_date`),
  KEY `idx_mb_passport` (`passport_number`),
  CONSTRAINT `fk_mb_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_mb_vendor` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `package_quotations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `quote_no` varchar(50) NOT NULL,
  `quote_date` date DEFAULT NULL,
  `client_name` varchar(150) DEFAULT NULL,
  `adults` int(10) unsigned NOT NULL DEFAULT 0,
  `children` int(10) unsigned NOT NULL DEFAULT 0,
  `infants` int(10) unsigned NOT NULL DEFAULT 0,
  `dep_date` date DEFAULT NULL,
  `ret_date` date DEFAULT NULL,
  `total_price` decimal(14,2) NOT NULL DEFAULT 0.00,
  `payload` longtext NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pq_quote_date` (`quote_date`),
  KEY `idx_pq_quote_no` (`quote_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `password_resets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `code_hash` varchar(255) NOT NULL,
  `attempts` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `expires_at` datetime NOT NULL,
  `used_at` datetime DEFAULT NULL,
  `request_ip` varchar(45) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_pr_user` (`user_id`,`used_at`),
  CONSTRAINT `fk_pr_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `system_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `transport_bookings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `master_booking_id` int(10) unsigned DEFAULT NULL,
  `hotel_booking_id` int(10) unsigned DEFAULT NULL,
  `voucher_id` int(10) unsigned DEFAULT NULL,
  `agent_id` int(10) unsigned NOT NULL,
  `vendor_id` int(10) unsigned DEFAULT NULL,
  `service_date` date NOT NULL,
  `flight_number` varchar(50) DEFAULT NULL,
  `terminal` varchar(100) DEFAULT 'Terminal 1',
  `pax_name` varchar(150) NOT NULL,
  `passport_number` varchar(50) DEFAULT NULL,
  `pax_count` int(10) unsigned DEFAULT 1,
  `vehicle_type` varchar(100) NOT NULL,
  `pickup_time` time NOT NULL,
  `route_details` varchar(255) DEFAULT 'JED-MAK',
  `buy_rate_sar` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sell_rate_sar` decimal(10,2) NOT NULL DEFAULT 0.00,
  `status` enum('scheduled','in_transit','completed','cancelled') DEFAULT 'scheduled',
  `auto_generated` tinyint(1) NOT NULL DEFAULT 0,
  `driver_name` varchar(100) DEFAULT NULL,
  `driver_contact` varchar(50) DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tb_service_date` (`service_date`),
  KEY `idx_tb_agent` (`agent_id`),
  KEY `idx_tb_mb` (`master_booking_id`),
  KEY `fk_tb_vendor` (`vendor_id`),
  KEY `idx_tb_hotel_booking` (`hotel_booking_id`),
  KEY `idx_tb_voucher` (`voucher_id`),
  CONSTRAINT `fk_tb_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tb_hotel_booking` FOREIGN KEY (`hotel_booking_id`) REFERENCES `hotel_bookings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tb_mb` FOREIGN KEY (`master_booking_id`) REFERENCES `master_bookings` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tb_vendor` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tb_voucher` FOREIGN KEY (`voucher_id`) REFERENCES `hotel_vouchers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `transport_transfers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `line_item_id` varchar(64) NOT NULL,
  `sequence` int(10) unsigned NOT NULL DEFAULT 1,
  `service_date` date DEFAULT NULL,
  `pickup_time` time DEFAULT NULL,
  `flight_number` varchar(50) DEFAULT NULL,
  `terminal` varchar(100) DEFAULT NULL,
  `pax_name` varchar(150) DEFAULT NULL,
  `passport_number` varchar(50) DEFAULT NULL,
  `pax_count` int(10) unsigned NOT NULL DEFAULT 1,
  `vehicle_type` varchar(100) DEFAULT NULL,
  `route_details` varchar(255) DEFAULT NULL,
  `buy_rate` decimal(12,2) NOT NULL DEFAULT 0.00,
  `sell_rate` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'SAR',
  `notes` varchar(255) DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tt_line_item` (`line_item_id`),
  KEY `idx_tt_booking` (`booking_id`),
  KEY `idx_tt_service_date` (`service_date`),
  CONSTRAINT `fk_tt_booking` FOREIGN KEY (`booking_id`) REFERENCES `master_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `user_remember_tokens` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `selector` varchar(24) NOT NULL,
  `validator_hash` varchar(64) NOT NULL,
  `expires_at` datetime NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `selector` (`selector`),
  KEY `idx_urt_user` (`user_id`),
  CONSTRAINT `fk_urt_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(150) DEFAULT NULL,
  `password_hash` varchar(255) NOT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `role` enum('admin','full_access','view_only') NOT NULL DEFAULT 'full_access',
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `last_login_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `uq_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `vendor_payments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `vendor_id` int(10) unsigned NOT NULL,
  `payment_date` date NOT NULL,
  `amount_sar` decimal(12,2) NOT NULL,
  `payment_mode` varchar(100) DEFAULT 'Direct Bank Transfer',
  `reference_number` varchar(100) DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_vp_vendor` (`vendor_id`),
  KEY `idx_vp_date` (`payment_date`),
  CONSTRAINT `fk_vp_vendor` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `vendors` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `company_name` varchar(150) DEFAULT NULL,
  `service_type` varchar(100) DEFAULT 'Visas & Hotel BRN',
  `phone` varchar(50) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `country` varchar(100) DEFAULT 'Saudi Arabia',
  `opening_payable_sar` decimal(12,2) DEFAULT 0.00,
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `voucher_mutamers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `voucher_id` int(10) unsigned NOT NULL,
  `mutamer_name` varchar(150) NOT NULL,
  `passport_number` varchar(50) NOT NULL,
  `gender` enum('M','F') NOT NULL,
  `is_adult` enum('Adult','Child','Infant') DEFAULT 'Adult',
  `bed_assigned` enum('Yes','No') DEFAULT 'Yes',
  PRIMARY KEY (`id`),
  KEY `idx_vm_passport` (`passport_number`),
  KEY `fk_vm_voucher` (`voucher_id`),
  CONSTRAINT `fk_vm_voucher` FOREIGN KEY (`voucher_id`) REFERENCES `hotel_vouchers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `voucher_stays` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `voucher_id` int(10) unsigned NOT NULL,
  `city` enum('Makkah','Madinah') NOT NULL,
  `hotel_name` varchar(150) NOT NULL,
  `room_type` varchar(100) DEFAULT 'Double Bed',
  `meal_plan` varchar(50) DEFAULT 'RO',
  `confirmation_number` varchar(100) DEFAULT NULL,
  `checkin_date` date NOT NULL,
  `checkout_date` date NOT NULL,
  `nights` int(10) unsigned NOT NULL,
  `buy_rate_per_night` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sell_rate_per_night` decimal(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `idx_vs_checkin` (`checkin_date`),
  KEY `idx_vs_checkout` (`checkout_date`),
  KEY `fk_vs_voucher` (`voucher_id`),
  CONSTRAINT `fk_vs_voucher` FOREIGN KEY (`voucher_id`) REFERENCES `hotel_vouchers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;
